{
 "title": "Staxx",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "VM Run Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vm_total_run_queue_lengths_cpu", "legendFormat": "CPU Queue Length" }
   ]
  },
  {
   "title": "Erlang VM Memory consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    { "expr": "vm_memory_total", "legendFormat": "Total" },
    { "expr": "vm_memory_processes_used", "legendFormat": "Processes Used" },
    { "expr": "vm_memory_binary", "legendFormat": "Binary used" }
   ]
  },
  {
   "title": "Deployments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "staxx_chain_deployment_started", "legendFormat": "Started" },
    { "expr": "staxx_chain_deployment_failed", "legendFormat": "Failed" },
    { "expr": "staxx_chain_deployment_success", "legendFormat": "Success" }
   ]
  },
  {
   "title": "Chains (EVM) processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "staxx_chain_start", "legendFormat": "Started" },
    { "expr": "staxx_chain_stop", "legendFormat": "Stopped" }
   ]
  },
  {
   "title": "Docker Containers Amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "staxx_docker_container_start", "legendFormat": "Started" },
    { "expr": "staxx_docker_container_stop", "legendFormat": "Stopped" }
   ]
  },
  {
   "title": "HTTP Response Status Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_responses_count", "legendFormat": "{{status}}" }
   ]
  }
 ]
}